# Output "0.14.0-filter-flicker-before.gif"
Output "0.14.0-filter-flicker-after.gif"
Set Theme "Tomorrow Night"
Set Width 1500
Set Height 800

Hide
# Type "csvlens Pokemon.csv"
Type "~/.cargo/bin/csvlens Pokemon.csv"
Sleep 0.5s
Enter @1s
Show

Type @0.1s "&"
Type @0.1s "Normal"
Enter @1s

Type @0.1s "&"
Type @0.1s "Flying"
Enter @1s

Type @0.1s "&"
Type @0.1s "Grass"
Enter @1s

Type @0.1s "&"
Type @0.1s "Ground"
Enter @1s